import { useCallback, useEffect, useMemo, useState } from "react";
import { View } from "react-native";
import { useLocalSearchParams } from "expo-router";
import AdminLayout, { AdminConfirmModal, AdminNotice, AdminPageState } from "../../shared/adminShared";
import api from "../../../../services/api";
import { getApiErrorMessage } from "../../../../services/http";
import type { GameKey, GamePlatformsResponse, PlatformConfirmationState, PlatformFormState, PlatformKeysState, PlatformMonitorItem, SaveKeysResponse } from "../../shared/admin.types";
import { createPlatformFormState, createPlatformKeysState, emptyKeysMeta, getGameKeyValues, hasPlatformPriceChanged, parsePlatformPrice, keysPageSize } from "./AdminGamePlatforms.helpers";
import AdminGamePlatformCard from "./AdminGamePlatformCard";
import AdminGamePlatformsHeader from "./AdminGamePlatformsHeader";
import AdminGamePlatformsModal from "./AdminGamePlatformsModal";

export default function AdminGamePlatforms({ gameId }: { gameId?: string }) {
  const params = useLocalSearchParams<{ gameId?: string }>(); const routeGameId = gameId ?? (Array.isArray(params.gameId) ? params.gameId[0] : params.gameId); const [game, setGame] = useState<GamePlatformsResponse["game"] | null>(null); const [platforms, setPlatforms] = useState<PlatformMonitorItem[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [selected, setSelected] = useState<PlatformMonitorItem | null>(null); const [form, setForm] = useState<PlatformFormState | null>(null); const [keys, setKeys] = useState<PlatformKeysState>(createPlatformKeysState()); const [pending, setPending] = useState<PlatformConfirmationState | null>(null);
  const currentPlatform = useMemo(() => selected ? platforms.find((item) => item.platform.id === selected.platform.id) ?? selected : null, [platforms, selected]);
  const load = useCallback(async () => { if (!routeGameId) { setError("Jogo inválido."); setLoading(false); return; } try { setLoading(true); setError(""); const data = await api.get<GamePlatformsResponse>(`/games/${routeGameId}/platforms`); setGame(data.game); setPlatforms(data.platforms ?? []); } catch (requestError) { setError(getApiErrorMessage(requestError, "Não foi possível carregar as plataformas do jogo.")); } finally { setLoading(false); } }, [routeGameId]);
  useEffect(() => { void load(); }, [load]);
  const loadKeys = useCallback(async (listingId: number | null, page = 1) => { if (!listingId) { setKeys(createPlatformKeysState()); return; } try { setKeys((current) => ({ ...current, isLoading: true, error: "", page })); const data = await api.get<{ items: GameKey[]; meta: typeof emptyKeysMeta }>(`/game-keys?page=${page}&limit=${keysPageSize}&listingId=${listingId}`); setKeys((current) => ({ ...current, isLoading: false, items: data.items ?? [], meta: data.meta ?? emptyKeysMeta, page, selectedIds: [] })); } catch (requestError) { setKeys((current) => ({ ...current, isLoading: false, items: [], error: getApiErrorMessage(requestError, "Não foi possível carregar as keys."), meta: emptyKeysMeta })); } }, []);
  const open = (platform: PlatformMonitorItem) => { setSelected(platform); setForm(createPlatformFormState(platform)); void loadKeys(platform.listingId); };
  const close = () => { setSelected(null); setForm(null); setPending(null); };
  const requestSave = () => { if (!selected || !form) return; if (!parsePlatformPrice(form.price)) { setForm((current) => current ? { ...current, error: "Informe um preço maior que zero." } : current); return; } if (hasPlatformPriceChanged(form)) { setPending({ type: "priceChange", platformId: selected.platform.id }); return; } void savePlatform(); };
  const savePlatform = async () => { if (!routeGameId || !selected || !form) return; try { setForm((current) => current ? { ...current, isSaving: true, error: "", success: "" } : current); const price = parsePlatformPrice(form.price); await api.put(`/games/${routeGameId}/platforms/${selected.platform.id}`, { price: price ?? undefined, isActive: form.isActive }); setForm((current) => current ? { ...current, originalPrice: form.price, isSaving: false, success: "Preço e status salvos com sucesso." } : current); setPending(null); await load(); } catch (requestError) { setForm((current) => current ? { ...current, isSaving: false, error: getApiErrorMessage(requestError, "Não foi possível salvar a plataforma.") } : current); } };
  const addKeys = async () => { if (!routeGameId || !selected || !form) return; const parsed = getGameKeyValues(form.newKeysText); if (!selected.hasListing || parsed.keyValues.length === 0 || parsed.hasIncompleteKey) { setForm((current) => current ? { ...current, error: "Informe keys completas no formato XXXX-XXXX-XXXX." } : current); return; } try { setForm((current) => current ? { ...current, isAddingKeys: true, error: "", success: "" } : current); const result = await api.post<SaveKeysResponse>(`/games/${routeGameId}/platforms/${selected.platform.id}/keys`, { keyValues: parsed.keyValues }); setForm((current) => current ? { ...current, newKeysText: "", isAddingKeys: false, success: `${result.createdCount} key(s) adicionada(s).` } : current); await load(); const next = platforms.find((item) => item.platform.id === selected.platform.id); await loadKeys(next?.listingId ?? selected.listingId, 1); } catch (requestError) { setForm((current) => current ? { ...current, isAddingKeys: false, error: getApiErrorMessage(requestError, "Não foi possível adicionar as keys.") } : current); } };
  const removeKeys = async () => { if (!selected?.listingId || keys.selectedIds.length === 0) return; try { setKeys((current) => ({ ...current, isRemoving: true, error: "" })); await api.post("/game-keys/bulk-delete", { listingId: selected.listingId, ids: keys.selectedIds }); setPending(null); await load(); await loadKeys(selected.listingId, keys.page); setKeys((current) => ({ ...current, isRemoving: false })); } catch (requestError) { setKeys((current) => ({ ...current, isRemoving: false, error: getApiErrorMessage(requestError, "Não foi possível remover as keys.") })); } };
  return <AdminLayout title="Monitor de plataformas" description="Controle preço, status e estoque de cada plataforma vinculada ao jogo." backTo="/admin/games"><AdminPageState loading={loading} error={error} isEmpty={!game} loadingText="Carregando plataformas..." emptyText="Jogo não encontrado.">{game ? <><AdminGamePlatformsHeader gameTitle={game.title} coverImageUrl={game.coverImageUrl} availableKeysCount={platforms.reduce((sum, item) => sum + item.stock.available, 0)} /><View style={{ gap: 12 }}>{platforms.map((platform) => <AdminGamePlatformCard key={platform.platform.id} platform={platform} onManage={() => open(platform)} />)}</View>{platforms.length === 0 ? <AdminNotice>Nenhuma plataforma cadastrada para monitorar.</AdminNotice> : null}</> : null}</AdminPageState><AdminGamePlatformsModal visible={Boolean(currentPlatform && form)} platform={currentPlatform} formState={form} keysState={keys} onClose={close} onPriceChange={(value) => setForm((current) => current ? { ...current, price: value, error: "" } : current)} onActiveChange={(value) => setForm((current) => current ? { ...current, isActive: value } : current)} onSave={requestSave} onNewKeysTextChange={(value) => setForm((current) => current ? { ...current, newKeysText: value, error: "" } : current)} onAddKeys={() => void addKeys()} onRemoveSelected={() => setPending({ type: "removeKeys", platformId: currentPlatform?.platform.id ?? 0 })} onToggleKey={(id) => setKeys((current) => ({ ...current, selectedIds: current.selectedIds.includes(id) ? current.selectedIds.filter((item) => item !== id) : [...current.selectedIds, id] }))} onPageChange={(nextPage) => { if (selected?.listingId) void loadKeys(selected.listingId, nextPage); }} /><AdminConfirmModal visible={Boolean(pending)} title={pending?.type === "priceChange" ? "Confirmar novo preço" : "Remover keys selecionadas"} message={pending?.type === "priceChange" ? `O novo preço será aplicado à plataforma ${selected?.platform.name ?? ""}.` : `${keys.selectedIds.length} key(s) disponível(is) selecionada(s) será(ão) removida(s).`} tone={pending?.type === "priceChange" ? "primary" : "danger"} processing={form?.isSaving || keys.isRemoving} onCancel={() => setPending(null)} onConfirm={() => { if (pending?.type === "priceChange") void savePlatform(); else void removeKeys(); }} /></AdminLayout>;
}
