import { useEffect, useState } from "react";
import { Text, View } from "react-native";
import { router } from "expo-router";
import AdminLayout, { AdminButton, AdminPageState, AdminSelectField, AdminTextField, AdminPagination, AdminStatusBadge, adminStyles, createEmptyMeta, formatDateTime, formatMoney } from "../shared/adminShared";
import api from "../../../services/api";
import { getApiErrorMessage } from "../../../services/http";
import type { AdminOrderSummary, PaginatedResponse } from "../shared/admin.types";

const labels: Record<string, string> = { pending: "Pendente", paid: "Pago", cancelled: "Cancelado" }; const paymentLabels: Record<string, string> = { pending: "Pendente", succeeded: "Aprovado", failed: "Falhou" }; const PAGE_SIZE = 10;
export default function AdminOrders() { const [items, setItems] = useState<AdminOrderSummary[]>([]); const [meta, setMeta] = useState(createEmptyMeta(PAGE_SIZE)); const [page, setPage] = useState(1); const [search, setSearch] = useState(""); const [status, setStatus] = useState(""); const [paymentStatus, setPaymentStatus] = useState(""); const [applied, setApplied] = useState({ search: "", status: "", paymentStatus: "" }); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  useEffect(() => { void (async () => { try { setLoading(true); setError(""); const params = new URLSearchParams({ page: String(page), limit: String(PAGE_SIZE) }); if (applied.search) params.set("q", applied.search); if (applied.status) params.set("status", applied.status); if (applied.paymentStatus) params.set("paymentStatus", applied.paymentStatus); const data = await api.get<PaginatedResponse<AdminOrderSummary>>(`/admin/orders?${params.toString()}`); setItems(data.items ?? []); setMeta(data.meta ?? createEmptyMeta(PAGE_SIZE)); } catch (requestError) { setItems([]); setError(getApiErrorMessage(requestError, "Não foi possível carregar os pedidos.")); } finally { setLoading(false); } })(); }, [applied, page]);
  const apply = () => { setPage(1); setApplied({ search: search.trim(), status, paymentStatus }); }; const clear = () => { setSearch(""); setStatus(""); setPaymentStatus(""); setApplied({ search: "", status: "", paymentStatus: "" }); setPage(1); };
  return <AdminLayout title="Pedidos" description="Consulta completa dos pedidos realizados na loja, com filtros e visualização detalhada." backTo="/admin"><View style={adminStyles.card}><AdminTextField label="Buscar por pedido, email ou usuário" value={search} onChangeText={setSearch} placeholder="NEX-12, email, admin" autoCapitalize="none" /><View style={styles.two}><AdminSelectField label="Status do pedido" value={status} options={[{ label: "Todos", value: "" }, ...Object.entries(labels).map(([value, label]) => ({ value, label }))]} onChange={setStatus} /><AdminSelectField label="Status do pagamento" value={paymentStatus} options={[{ label: "Todos", value: "" }, ...Object.entries(paymentLabels).map(([value, label]) => ({ value, label }))]} onChange={setPaymentStatus} /></View><View style={adminStyles.wrap}><AdminButton onPress={apply}>Aplicar filtros</AdminButton><AdminButton tone="secondary" onPress={clear}>Limpar</AdminButton></View></View><AdminPageState loading={loading} error={error} isEmpty={items.length === 0} loadingText="Carregando pedidos..." emptyText="Nenhum pedido encontrado para os filtros aplicados."><View style={{ gap: 12 }}><Text style={adminStyles.muted}>{meta.total} pedido(s) encontrado(s)</Text>{items.map((order) => <View key={order.id} style={adminStyles.card}><View style={styles.orderHeader}><View style={{ flex: 1 }}><Text style={styles.orderNumber}>{order.orderNumber}</Text><Text style={adminStyles.description}>{order.user?.fullName || order.user?.username || "Usuário"} · {order.user?.email || "Sem email"}</Text><Text style={adminStyles.muted}>{order.itemCount} item(ns) · {formatDateTime(order.createdAt)}</Text></View><Text style={styles.total}>{formatMoney(order.totalAmount)}</Text></View><View style={[adminStyles.wrap, { marginTop: 10 }]}><AdminStatusBadge active={order.status === "paid"} activeLabel={`Pedido ${labels[order.status] ?? order.status}`} inactiveLabel={`Pedido ${labels[order.status] ?? order.status}`} /><AdminStatusBadge active={order.paymentStatus === "succeeded"} activeLabel={`Pagamento ${paymentLabels[order.paymentStatus] ?? order.paymentStatus}`} inactiveLabel={`Pagamento ${paymentLabels[order.paymentStatus] ?? order.paymentStatus}`} /></View><AdminButton onPress={() => router.push(`/admin/orders/${order.id}` as never)} style={{ alignSelf: "flex-start", marginTop: 12 }}>Ver detalhes</AdminButton></View>)}<AdminPagination meta={meta} onPageChange={setPage} /></View></AdminPageState></AdminLayout>;
}
const styles = { two: { flexDirection: "row" as const, gap: 12 }, orderHeader: { flexDirection: "row" as const, alignItems: "flex-start" as const, gap: 12 }, orderNumber: { color: "#ffffff", fontSize: 19, fontWeight: "800" as const, marginBottom: 6 }, total: { color: "#bfdbfe", fontSize: 20, fontWeight: "800" as const } };
