import { useEffect, useMemo, useState } from "react";
import { Image, Text, View } from "react-native";
import { useLocalSearchParams } from "expo-router";
import AdminLayout, { AdminNotice, AdminPageState, AdminPagination, AdminStatusBadge, adminStyles, formatDateTime, formatMoney } from "../shared/adminShared";
import api from "../../../services/api";
import { resolveAssetUrl } from "../../../services/assets";
import { getApiErrorMessage } from "../../../services/http";
import type { AdminOrderDetails as OrderDetails } from "../shared/admin.types";

const PER_PAGE = 6;
export default function AdminOrderDetails({ orderId }: { orderId?: string }) { const params = useLocalSearchParams<{ id?: string }>(); const id = orderId ?? (Array.isArray(params.id) ? params.id[0] : params.id); const [order, setOrder] = useState<OrderDetails | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [page, setPage] = useState(1); useEffect(() => { if (!id) { setError("Pedido inválido."); setLoading(false); return; } void api.get<OrderDetails>(`/admin/orders/${id}`).then(setOrder).catch((requestError) => setError(getApiErrorMessage(requestError, "Não foi possível carregar o pedido."))).finally(() => setLoading(false)); }, [id]); const visible = useMemo(() => order?.items.slice((page - 1) * PER_PAGE, page * PER_PAGE) ?? [], [order, page]);
  return <AdminLayout title={order ? `Pedido ${order.orderNumber}` : "Detalhes do pedido"} description="Visualização completa do pedido, do comprador e das licenças entregues." backTo="/admin/orders"><AdminPageState loading={loading} error={error} isEmpty={!order} loadingText="Carregando pedido..." emptyText="Pedido não encontrado.">{order ? <View style={{ gap: 14 }}><View style={styles.two}><View style={[adminStyles.card, { flex: 1 }]}><AdminStatusBadge active={order.status === "paid"} activeLabel={`Status: ${translate(order.status)}`} inactiveLabel={`Status: ${translate(order.status)}`} /><View style={styles.metrics}><Metric label="Subtotal" value={formatMoney(order.subtotal)} /><Metric label="Desconto" value={formatMoney(order.discountAmount)} /><Metric label="Total" value={formatMoney(order.totalAmount)} /></View></View><View style={[adminStyles.card, { flex: 1 }]}><Text style={styles.kicker}>CLIENTE</Text><Text style={adminStyles.sectionTitle}>{order.user?.fullName || order.user?.username || "Usuário"}</Text><Text style={adminStyles.description}>{order.user?.email || "Sem email"}</Text><Text style={adminStyles.muted}>CPF: {order.user?.cpf || "Não informado"}</Text><Text style={adminStyles.muted}>Método: {order.paymentMethod || "-"}</Text></View></View><View style={adminStyles.card}><Text style={adminStyles.sectionTitle}>Timeline básica</Text><View style={styles.timeline}><Metric label="Criado" value={formatDateTime(order.createdAt)} /><Metric label="Pagamento confirmado" value={formatDateTime(order.paymentConfirmedAt)} /><Metric label="Cancelado" value={formatDateTime(order.cancelledAt)} /></View></View><View style={{ gap: 10 }}><View style={styles.itemsHeader}><Text style={adminStyles.sectionTitle}>Itens do pedido</Text><Text style={adminStyles.muted}>{order.items.length} item(ns)</Text></View>{order.items.length === 0 ? <AdminNotice>Este pedido não possui itens cadastrados.</AdminNotice> : visible.map((item) => <View key={item.id} style={styles.item}><Image source={{ uri: resolveAssetUrl(item.listing?.game?.coverImageUrl) }} style={styles.itemImage} resizeMode="cover" /><View style={{ flex: 1 }}><Text style={adminStyles.sectionTitle}>{item.listing?.game?.title || "Jogo"}</Text><Text style={adminStyles.description}>{item.listing?.platform?.name || "Plataforma"}</Text><Text style={adminStyles.muted}>Item #{item.id} · Oferta #{item.listingId}</Text></View><View style={{ alignItems: "flex-end" }}><Text style={styles.total}>{formatMoney(item.price)}</Text><Text style={adminStyles.muted}>{formatDateTime(item.createdAt)}</Text></View></View>)}{order.items.length > PER_PAGE ? <AdminPagination meta={{ page, limit: PER_PAGE, total: order.items.length, totalPages: Math.ceil(order.items.length / PER_PAGE) }} onPageChange={setPage} /> : null}</View></View> : null}</AdminPageState></AdminLayout>; }
function Metric({ label, value }: { label: string; value: string }) { return <View style={{ flex: 1, gap: 5 }}><Text style={styles.kicker}>{label.toUpperCase()}</Text><Text style={styles.metric}>{value}</Text></View>; }
function translate(value?: string) { return value === "paid" ? "Pago" : value === "pending" ? "Pendente" : value === "cancelled" ? "Cancelado" : value || "-"; }
const styles = { two: { flexDirection: "row" as const, gap: 12 }, metrics: { flexDirection: "row" as const, gap: 12, marginTop: 16 }, metric: { color: "#ffffff", fontSize: 18, fontWeight: "800" as const }, kicker: { color: "#64748b", fontSize: 10, fontWeight: "800" as const, letterSpacing: 1.2 }, timeline: { flexDirection: "row" as const, gap: 12, marginTop: 14 }, itemsHeader: { flexDirection: "row" as const, alignItems: "center" as const, justifyContent: "space-between" as const }, item: { flexDirection: "row" as const, alignItems: "center" as const, gap: 10, borderWidth: 1, borderColor: "#1e293b", borderRadius: 16, backgroundColor: "#020617", padding: 10 }, itemImage: { width: 88, height: 68, borderRadius: 12, backgroundColor: "#0f172a" }, total: { color: "#bfdbfe", fontSize: 19, fontWeight: "800" as const } };
