import { useEffect, useState } from "react";
import { Text, View } from "react-native";
import { useLocalSearchParams } from "expo-router";
import AdminLayout, { AdminButton, AdminPageState, AdminPagination, AdminTextField, adminStyles, createEmptyMeta, formatDateTime, formatMoney } from "../shared/adminShared";
import api from "../../../services/api";
import { getApiErrorMessage } from "../../../services/http";
import type { AdminPriceHistoryItem, PaginatedResponse } from "../shared/admin.types";

const PAGE_SIZE = 12;
export default function AdminPriceHistory() { const params = useLocalSearchParams<{ listingId?: string }>(); const initialListing = Array.isArray(params.listingId) ? params.listingId[0] : params.listingId; const [items, setItems] = useState<AdminPriceHistoryItem[]>([]); const [meta, setMeta] = useState(createEmptyMeta(PAGE_SIZE)); const [page, setPage] = useState(1); const [search, setSearch] = useState(""); const [listingId, setListingId] = useState(initialListing ?? ""); const [applied, setApplied] = useState({ search: "", listingId: initialListing ?? "" }); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); useEffect(() => { void (async () => { try { setLoading(true); setError(""); const query = new URLSearchParams({ page: String(page), limit: String(PAGE_SIZE) }); if (applied.search) query.set("q", applied.search); if (applied.listingId) query.set("listingId", applied.listingId); const data = await api.get<PaginatedResponse<AdminPriceHistoryItem>>(`/admin/price-history?${query.toString()}`); setItems(data.items ?? []); setMeta(data.meta ?? createEmptyMeta(PAGE_SIZE)); } catch (requestError) { setItems([]); setError(getApiErrorMessage(requestError, "Não foi possível carregar o histórico de preço.")); } finally { setLoading(false); } })(); }, [applied, page]); const apply = () => { setPage(1); setApplied({ search: search.trim(), listingId: listingId.replace(/\D/g, "") }); }; const clear = () => { setSearch(""); setListingId(""); setApplied({ search: "", listingId: "" }); setPage(1); };
  return <AdminLayout title="Auditoria de preço" description="Histórico do preço base por jogo e plataforma, com responsável e data da alteração." backTo="/admin"><View style={adminStyles.card}><AdminTextField label="Buscar por jogo, plataforma ou admin" value={search} onChangeText={setSearch} placeholder="Hollow Knight, Steam, admin" /><AdminTextField label="Oferta ID" value={listingId} onChangeText={(value) => setListingId(value.replace(/\D/g, ""))} placeholder="Ex.: 14" keyboardType="numeric" /><View style={adminStyles.wrap}><AdminButton onPress={apply}>Aplicar filtros</AdminButton><AdminButton tone="secondary" onPress={clear}>Limpar</AdminButton></View></View><AdminPageState loading={loading} error={error} isEmpty={items.length === 0} loadingText="Carregando histórico..." emptyText="Nenhuma alteração de preço encontrada."><View style={{ gap: 12 }}><Text style={adminStyles.muted}>{meta.total} alteração(ões) encontrada(s)</Text>{items.map((item) => <View key={item.id} style={adminStyles.card}><Text style={adminStyles.sectionTitle}>{item.game?.title || "Jogo"} · {item.platform?.name || "Plataforma"}</Text><Text style={adminStyles.muted}>Oferta #{item.listingId} · {formatDateTime(item.createdAt)}</Text><Text style={[adminStyles.description, { marginTop: 6 }]}>Responsável: {item.changedBy?.username || item.changedBy?.email || "Não identificado"}</Text><View style={styles.prices}><Metric label="Preço anterior" value={item.previousPrice === null ? "Cadastro inicial" : formatMoney(item.previousPrice)} /><Metric label="Novo preço" value={formatMoney(item.nextPrice)} /></View></View>)}<AdminPagination meta={meta} onPageChange={setPage} /></View></AdminPageState></AdminLayout>; }
function Metric({ label, value }: { label: string; value: string }) { return <View style={styles.metric}><Text style={styles.label}>{label.toUpperCase()}</Text><Text style={styles.value}>{value}</Text></View>; }
const styles = { prices: { flexDirection: "row" as const, flexWrap: "wrap" as const, gap: 10, marginTop: 14 }, metric: { flex: 1, minWidth: 150, borderWidth: 1, borderColor: "#1e293b", borderRadius: 14, backgroundColor: "#0f172a", padding: 12 }, label: { color: "#64748b", fontSize: 10, fontWeight: "800" as const, letterSpacing: 1.1 }, value: { color: "#ffffff", fontSize: 17, fontWeight: "800" as const, marginTop: 6 } };
