import Ionicons from "@expo/vector-icons/Ionicons";
import { router } from "expo-router";
import { useCallback, useEffect, useState } from "react";
import { ActivityIndicator, Image, Pressable, RefreshControl, ScrollView, StatusBar, StyleSheet, Text, useWindowDimensions, View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { useAuth } from "../contexts/useAuth";
import api from "../services/api";
import { resolveAssetUrl } from "../services/assets";
import { getApiErrorMessage } from "../services/http";
import type { WishlistItem, WishlistResponse } from "../components/user/account.types";

export default function Favorites() {
  const { width } = useWindowDimensions();
  const compact = width < 760;
  const { isAuthenticated, isReady } = useAuth();
  const [items, setItems] = useState<WishlistItem[]>([]);
  const [loading, setLoading] = useState(true);
  const [refreshing, setRefreshing] = useState(false);
  const [removingId, setRemovingId] = useState<number | null>(null);
  const [error, setError] = useState("");

  const load = useCallback(async () => {
    if (!isReady || !isAuthenticated) { setLoading(false); return; }
    try { setLoading(true); setError(""); const data = await api.get<WishlistResponse>("/wishlists"); setItems(data.items ?? []); }
    catch (requestError) { setItems([]); setError(getApiErrorMessage(requestError, "Não foi possível carregar seus favoritos.")); }
    finally { setLoading(false); }
  }, [isAuthenticated, isReady]);

  useEffect(() => { void load(); }, [load]);
  const refresh = async () => { setRefreshing(true); await load(); setRefreshing(false); };
  const remove = async (gameId: number) => { try { setRemovingId(gameId); await api.delete(`/wishlists/${gameId}`); setItems((current) => current.filter((item) => item.gameId !== gameId)); } catch (requestError) { setError(getApiErrorMessage(requestError, "Não foi possível remover este favorito.")); } finally { setRemovingId(null); } };

  if (!isReady || loading) return <SafeAreaView style={styles.safeArea}><View style={styles.center}><ActivityIndicator color="#67e8f9" /><Text style={styles.meta}>Carregando favoritos...</Text></View></SafeAreaView>;
  if (!isAuthenticated) return <SafeAreaView style={styles.safeArea}><View style={styles.center}><Ionicons name="lock-closed-outline" size={38} color="#67e8f9" /><Text style={styles.emptyTitle}>Entre para acessar seus favoritos</Text><Pressable onPress={() => router.replace("/login")} style={styles.primaryButton}><Text style={styles.primaryText}>Abrir tela de login</Text></Pressable></View></SafeAreaView>;
  return <SafeAreaView style={styles.safeArea} edges={["top"]}><StatusBar barStyle="light-content" /><ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={() => void refresh()} tintColor="#67e8f9" colors={["#2563eb"]} />}><Pressable onPress={() => router.back()} style={styles.back}><Ionicons name="arrow-back" size={18} color="#cbd5e1" /><Text style={styles.backText}>Voltar</Text></Pressable><Text accessibilityRole="header" style={styles.title}>Meus favoritos</Text><Text style={styles.subtitle}>Guarde jogos para comparar depois e decidir a plataforma com calma.</Text>{error ? <View style={styles.feedback}><Text style={styles.feedbackText}>{error}</Text><Pressable onPress={() => void load()}><Text style={styles.retryText}>Tentar novamente</Text></Pressable></View> : null}{!error && items.length === 0 ? <View style={styles.empty}><Ionicons name="heart-outline" size={36} color="#fb7185" /><Text style={styles.emptyTitle}>Você ainda não favoritou nenhum jogo</Text><Text style={styles.emptyText}>Toque no coração de um jogo para guardá-lo nesta lista.</Text><Pressable onPress={() => router.replace("/(tabs)/loja" as never)} style={styles.primaryButton}><Text style={styles.primaryText}>Explorar a loja</Text></Pressable></View> : null}{!error && items.length > 0 ? <View style={styles.list}>{items.map((item) => { const game = item.game; return <View key={item.id} style={[styles.card, !compact && styles.cardWide]}>{game?.coverImageUrl ? <Image source={{ uri: resolveAssetUrl(game.coverImageUrl) }} style={styles.cover} resizeMode="cover" accessibilityLabel={game.title ?? "Jogo"} /> : <View style={styles.coverFallback}><Ionicons name="image-outline" size={34} color="#475569" /></View>}<View style={styles.cardBody}><Text style={styles.cardTitle} numberOfLines={2}>{game?.title ?? "Jogo"}</Text><Text style={styles.meta}>{game?.categories?.[0]?.name ?? "Sem categoria"}</Text><View style={styles.actions}><Pressable onPress={() => router.push({ pathname: "/loja/[gameId]", params: { gameId: String(item.gameId) } } as never)} style={styles.secondaryButton}><Text style={styles.secondaryText}>Ver jogo</Text></Pressable><Pressable accessibilityLabel={`Remover ${game?.title ?? "jogo"} dos favoritos`} disabled={removingId === item.gameId} onPress={() => void remove(item.gameId)} style={styles.removeButton}><Ionicons name="heart-dislike-outline" size={17} color="#fecdd3" /><Text style={styles.removeText}>{removingId === item.gameId ? "Removendo..." : "Remover"}</Text></Pressable></View></View></View>; })}</View> : null}</ScrollView></SafeAreaView>;
}

const styles = StyleSheet.create({ safeArea: { flex: 1, backgroundColor: "#020617" }, content: { width: "100%", maxWidth: 960, alignSelf: "center", padding: 20, paddingBottom: 40 }, center: { flex: 1, minHeight: 260, alignItems: "center", justifyContent: "center", padding: 28, gap: 10 }, back: { minHeight: 48, alignSelf: "flex-start", flexDirection: "row", alignItems: "center", gap: 8 }, backText: { color: "#cbd5e1", fontSize: 14, fontWeight: "700" }, title: { marginTop: 14, color: "#fff", fontSize: 30, fontWeight: "900" }, subtitle: { marginTop: 8, color: "#cbd5e1", fontSize: 14, lineHeight: 21 }, list: { flexDirection: "row", flexWrap: "wrap", gap: 12, marginTop: 22 }, card: { width: "100%", overflow: "hidden", borderWidth: 1, borderColor: "#334155", borderRadius: 16, backgroundColor: "#0f172a" }, cardWide: { width: "49%" }, cover: { width: "100%", aspectRatio: 16 / 8, backgroundColor: "#020617" }, coverFallback: { width: "100%", aspectRatio: 16 / 8, alignItems: "center", justifyContent: "center", backgroundColor: "#020617" }, cardBody: { padding: 16 }, cardTitle: { color: "#fff", fontSize: 18, fontWeight: "800" }, meta: { marginTop: 5, color: "#94a3b8", fontSize: 12 }, actions: { marginTop: 14, flexDirection: "row", flexWrap: "wrap", gap: 8 }, secondaryButton: { minHeight: 48, minWidth: 118, flex: 1, alignItems: "center", justifyContent: "center", borderWidth: 1, borderColor: "#475569", borderRadius: 11, backgroundColor: "#020617" }, secondaryText: { color: "#e2e8f0", fontSize: 13, fontWeight: "800" }, removeButton: { minHeight: 48, minWidth: 118, flex: 1, alignItems: "center", justifyContent: "center", flexDirection: "row", gap: 6, borderWidth: 1, borderColor: "rgba(244,63,94,0.4)", borderRadius: 11, backgroundColor: "rgba(244,63,94,0.08)" }, removeText: { color: "#fecdd3", fontSize: 13, fontWeight: "800" }, empty: { marginTop: 22, padding: 24, alignItems: "center", borderWidth: 1, borderColor: "#334155", borderRadius: 16, backgroundColor: "#0f172a" }, emptyTitle: { marginTop: 10, color: "#fff", fontSize: 20, fontWeight: "900", textAlign: "center" }, emptyText: { marginTop: 8, color: "#94a3b8", fontSize: 14, lineHeight: 21, textAlign: "center" }, primaryButton: { minHeight: 48, marginTop: 18, paddingHorizontal: 18, alignItems: "center", justifyContent: "center", borderRadius: 12, backgroundColor: "#2563eb" }, primaryText: { color: "#fff", fontSize: 14, fontWeight: "800" }, feedback: { marginTop: 18, padding: 14, borderWidth: 1, borderColor: "rgba(244,63,94,0.4)", borderRadius: 12, backgroundColor: "rgba(244,63,94,0.1)" }, feedbackText: { color: "#fecdd3", fontSize: 14, lineHeight: 20 }, retryText: { marginTop: 8, color: "#fda4af", fontSize: 13, fontWeight: "800" } });
