import Ionicons from "@expo/vector-icons/Ionicons";
import { useCallback, useEffect, useState } from "react";
import { Image, Text, TextInput, View } from "react-native";
import { router } from "expo-router";
import AdminLayout, { AdminButton, AdminConfirmModal, AdminLinkButton, AdminPageState, AdminPagination, AdminStatusBadge, adminStyles, createEmptyMeta, formatReleaseDate } from "../shared/adminShared";
import api from "../../../services/api";
import { resolveAssetUrl } from "../../../services/assets";
import { getApiErrorMessage } from "../../../services/http";
import type { PaginatedResponse } from "../shared/admin.types";

type Game = { id: number; title: string; description: string; coverImageUrl?: string; releaseDate: string; isActive?: boolean };
const PAGE_SIZE = 9;
export default function AdminGames() {
  const [items, setItems] = useState<Game[]>([]); const [meta, setMeta] = useState(createEmptyMeta(PAGE_SIZE)); const [page, setPage] = useState(1); const [query, setQuery] = useState(""); const [appliedQuery, setAppliedQuery] = useState(""); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [pending, setPending] = useState<Game | null>(null); const [deleting, setDeleting] = useState(false);
  const load = useCallback(async () => { try { setLoading(true); setError(""); const suffix = appliedQuery ? `&q=${encodeURIComponent(appliedQuery)}` : ""; const data = await api.get<PaginatedResponse<Game>>(`/games?page=${page}&limit=${PAGE_SIZE}${suffix}`); setItems(data.items ?? []); setMeta(data.meta ?? createEmptyMeta(PAGE_SIZE)); } catch (requestError) { setItems([]); setError(getApiErrorMessage(requestError, "Não foi possível carregar os jogos.")); } finally { setLoading(false); } }, [appliedQuery, page]);
  useEffect(() => { void load(); }, [load]);
  const remove = async () => { if (!pending) return; try { setDeleting(true); await api.delete(`/games/${pending.id}`); setPending(null); if (items.length === 1 && page > 1) setPage((current) => current - 1); else await load(); } catch (requestError) { setPending(null); setError(getApiErrorMessage(requestError, "Não foi possível excluir o jogo.")); } finally { setDeleting(false); } };
  return <AdminLayout title="Jogos" description="Cadastre jogos, ajuste o editorial e abra o monitor por plataforma." backTo="/admin" actions={<AdminLinkButton to="/admin/games/new">Novo jogo</AdminLinkButton>}><View style={adminStyles.card}><View style={adminStyles.row}><View style={styles.search}><Ionicons name="search" size={18} color="#64748b" /><TextInput value={query} onChangeText={setQuery} onSubmitEditing={() => { setAppliedQuery(query.trim()); setPage(1); }} placeholder="Pesquisar por título..." placeholderTextColor="#64748b" style={styles.searchInput} returnKeyType="search" /></View><AdminButton onPress={() => { setAppliedQuery(query.trim()); setPage(1); }}>Buscar</AdminButton></View><Text style={[adminStyles.muted, { marginTop: 10 }]}>{meta.total} resultado(s)</Text></View><AdminPageState loading={loading} error={error} isEmpty={items.length === 0} loadingText="Carregando jogos..." emptyText={appliedQuery ? "Nenhum jogo encontrado para essa busca." : "Nenhum jogo cadastrado."}><View style={styles.grid}>{items.map((game) => <View key={game.id} style={adminStyles.card}><Image source={{ uri: resolveAssetUrl(game.coverImageUrl) }} style={styles.cover} resizeMode="cover" /><View style={styles.gameHeader}><View style={{ flex: 1 }}><Text style={styles.title} numberOfLines={2}>{game.title}</Text><Text style={adminStyles.muted}>Lançamento: {formatReleaseDate(game.releaseDate)}</Text></View><AdminStatusBadge active={game.isActive} /></View><Text style={styles.description} numberOfLines={3}>{game.description}</Text><View style={styles.actions}><AdminButton tone="secondary" onPress={() => router.push(`/admin/games/${game.id}/edit` as never)} style={{ flex: 1 }}>Editar</AdminButton><AdminButton tone="secondary" onPress={() => router.push(`/admin/games/${game.id}/platforms` as never)} style={{ flex: 1 }}>Plataformas</AdminButton><AdminButton tone="subtleDanger" onPress={() => setPending(game)} style={{ flex: 1 }}>{deleting && pending?.id === game.id ? "Excluindo..." : "Excluir"}</AdminButton></View></View>)}</View><AdminPagination meta={meta} onPageChange={setPage} /></AdminPageState><AdminConfirmModal visible={Boolean(pending)} title="Excluir jogo" message={`Tem certeza que deseja excluir o jogo ${pending?.title ?? ""}?`} processing={deleting} tone="danger" onCancel={() => setPending(null)} onConfirm={() => void remove()} /></AdminLayout>;
}
const styles = { search: { flex: 1, minWidth: 210, minHeight: 48, flexDirection: "row" as const, alignItems: "center" as const, gap: 8, borderWidth: 1, borderColor: "#334155", borderRadius: 14, backgroundColor: "#020617", paddingHorizontal: 12 }, searchInput: { flex: 1, color: "#ffffff", fontSize: 15 }, grid: { gap: 14 }, cover: { width: "100%" as const, aspectRatio: 16 / 8, borderRadius: 16, borderWidth: 1, borderColor: "#1e293b", backgroundColor: "#020617" }, gameHeader: { flexDirection: "row" as const, flexWrap: "wrap" as const, alignItems: "flex-start" as const, gap: 8, marginTop: 12 }, title: { color: "#ffffff", fontSize: 17, fontWeight: "700" as const, lineHeight: 22 }, description: { minHeight: 58, color: "#cbd5e1", fontSize: 13, lineHeight: 19, marginTop: 8 }, actions: { flexDirection: "row" as const, flexWrap: "wrap" as const, gap: 6, marginTop: 12 } };
