import Ionicons from "@expo/vector-icons/Ionicons";
import { Image, Text, View } from "react-native";
import { AdminButton, AdminTextField, adminColors, adminStyles } from "../shared/adminShared";
import { resolvePreviewUrl } from "../../../services/assets";
import type { GalleryItem, GameValues, UploadFile } from "../shared/admin.types";

export default function AdminGameFormMedia({ values, coverFile, coverPreviewUrl, galleryItems, galleryUrlInput, onCoverFile, onClearCover, onSetCoverUrl, onGalleryUrlChange, onAddGalleryUrl, onAddGalleryFile, onMoveGallery, onRemoveGallery }: { values: GameValues; coverFile: UploadFile | null; coverPreviewUrl: string; galleryItems: GalleryItem[]; galleryUrlInput: string; onCoverFile: (file: UploadFile | null) => void; onClearCover: () => void; onSetCoverUrl: (value: string) => void; onGalleryUrlChange: (value: string) => void; onAddGalleryUrl: () => void; onAddGalleryFile: (file: UploadFile) => void; onMoveGallery: (key: string, direction: -1 | 1) => void; onRemoveGallery: (key: string) => void }) {
  return <><View style={adminStyles.card}><View style={adminStyles.row}><Ionicons name="cloud-upload-outline" size={22} color={adminColors.cyan} /><View style={{ flex: 1 }}><Text style={adminStyles.sectionTitle}>Capa principal</Text><Text style={adminStyles.muted}>Escolha uma imagem ou use uma URL de fallback.</Text></View></View><View style={styles.preview}><Image source={{ uri: resolvePreviewUrl(coverPreviewUrl) }} style={styles.previewImage} resizeMode="cover" /></View><AdminButton tone="secondary" onPress={() => onFileSelected(onCoverFile)}>Escolher capa</AdminButton>{coverFile ? <View style={adminStyles.row}><Text style={adminStyles.muted} numberOfLines={1}>{coverFile.name}</Text><AdminButton tone="subtleDanger" onPress={onClearCover}>Remover</AdminButton></View> : null}<AdminTextField label="URL da capa" value={values.coverImageUrl} onChangeText={onSetCoverUrl} placeholder="https://..." note="O arquivo enviado tem prioridade." autoCapitalize="none" /></View><View style={adminStyles.card}><View style={adminStyles.row}><Ionicons name="images-outline" size={22} color={adminColors.cyan} /><View style={{ flex: 1 }}><Text style={adminStyles.sectionTitle}>Galeria</Text><Text style={adminStyles.muted}>Imagens extras podem ser enviadas ou cadastradas por URL.</Text></View></View><View style={styles.galleryActions}><AdminButton tone="secondary" onPress={() => onFileSelected((file) => { if (file) onAddGalleryFile(file); })}>Adicionar imagem</AdminButton><View style={{ flex: 1 }}><AdminTextField label="URL da galeria" value={galleryUrlInput} onChangeText={onGalleryUrlChange} placeholder="https://..." autoCapitalize="none" /></View><AdminButton tone="secondary" onPress={onAddGalleryUrl}>Adicionar URL</AdminButton></View>{galleryItems.length === 0 ? <Text style={[adminStyles.muted, styles.empty]}>Nenhuma imagem extra adicionada. A galeria é opcional.</Text> : <View style={{ gap: 10 }}>{galleryItems.map((item, index) => <View key={item.key} style={styles.galleryItem}><Image source={{ uri: resolvePreviewUrl(item.previewUrl) }} style={styles.galleryImage} resizeMode="cover" /><View style={{ flex: 1 }}><Text style={adminStyles.label} numberOfLines={1}>{item.kind === "file" ? item.file?.name : item.kind === "url" ? "Imagem por URL" : "Imagem atual"}</Text><Text style={adminStyles.muted}>Ordem {index + 1}</Text></View><View style={styles.galleryButtons}><AdminButton tone="secondary" disabled={index === 0} onPress={() => onMoveGallery(item.key, -1)}>↑</AdminButton><AdminButton tone="secondary" disabled={index === galleryItems.length - 1} onPress={() => onMoveGallery(item.key, 1)}>↓</AdminButton><AdminButton tone="subtleDanger" onPress={() => onRemoveGallery(item.key)}>×</AdminButton></View></View>)}</View>}</View></>;
}

async function onFileSelected(callback: (file: UploadFile | null) => void) {
  try {
    const ImagePicker = await import("expo-image-picker");
    const permission = await ImagePicker.requestMediaLibraryPermissionsAsync();
    if (!permission.granted) return;
    const result = await ImagePicker.launchImageLibraryAsync({ mediaTypes: ["images"], allowsEditing: false, quality: 0.85 });
    if (result.canceled) return;
    const asset = result.assets[0];
    if (!asset) return;
    callback({ uri: asset.uri, name: asset.fileName ?? `imagem-${Date.now()}.jpg`, type: asset.mimeType ?? "image/jpeg", file: asset.file });
  } catch { /* A tela principal continuará disponível mesmo sem o seletor. */ }
}

const styles = { preview: { height: 190, marginTop: 12, overflow: "hidden" as const, borderWidth: 1, borderColor: "#1e293b", borderRadius: 18, backgroundColor: "#0f172a" }, previewImage: { width: "100%" as const, height: "100%" as const }, galleryActions: { gap: 10, marginTop: 14 }, empty: { borderWidth: 1, borderColor: "#1e293b", borderRadius: 14, backgroundColor: "#0f172a", padding: 14, marginTop: 12 }, galleryItem: { flexDirection: "row" as const, alignItems: "center" as const, gap: 10, borderWidth: 1, borderColor: "#1e293b", borderRadius: 14, backgroundColor: "#0f172a", padding: 10 }, galleryImage: { width: 78, height: 58, borderRadius: 10, backgroundColor: "#020617" }, galleryButtons: { flexDirection: "row" as const, gap: 4 } };
