import { useEffect, useMemo, useState } from "react";
import { Text, View } from "react-native";
import { router } from "expo-router";
import AdminLayout, { AdminButton, AdminFormActions, AdminNotice, AdminPageState, AdminTextField, AdminTextareaField, AdminToggleField, adminStyles } from "../shared/adminShared";
import AdminGameFormMedia from "./AdminGameFormMedia";
import { buildGameFormData, createExistingGalleryItem, createUploadGalleryItem, createUrlGalleryItem, emptyGame, mapGameToValues, moveItem } from "./AdminGameForm.helpers";
import api from "../../../services/api";
import { resolveAssetUrl } from "../../../services/assets";
import { getApiErrorMessage } from "../../../services/http";
import type { Category, GalleryItem, GameResponse, GameValues, PaginatedResponse, UploadFile } from "../shared/admin.types";

export default function AdminGameForm({ id }: { id?: string }) {
  const editing = Boolean(id); const [values, setValues] = useState<GameValues>(emptyGame); const [categories, setCategories] = useState<Category[]>([]); const [gallery, setGallery] = useState<GalleryItem[]>([]); const [coverFile, setCoverFile] = useState<UploadFile | null>(null); const [galleryUrl, setGalleryUrl] = useState(""); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState(""); const [titleError, setTitleError] = useState(""); const [success, setSuccess] = useState("");
  useEffect(() => { let active = true; const load = async () => { try { setLoading(true); setError(""); const [categoryData, gameData] = await Promise.all([api.get<PaginatedResponse<Category>>("/categories?page=1&limit=100"), id ? api.get<GameResponse>(`/games/${id}`) : Promise.resolve(null)]); if (!active) return; setCategories(categoryData.items ?? []); if (gameData) { setValues(mapGameToValues(gameData)); setGallery((gameData.images ?? []).map(createExistingGalleryItem)); } else { setValues(emptyGame); setGallery([]); } setCoverFile(null); } catch (requestError) { if (active) setError(getApiErrorMessage(requestError, "Não foi possível carregar o formulário do jogo.")); } finally { if (active) setLoading(false); } }; void load(); return () => { active = false; }; }, [id]);
  const selectedCategories = useMemo(() => categories.filter((category) => values.categoryIds.includes(category.id)), [categories, values.categoryIds]);
  const setField = <Field extends keyof GameValues>(field: Field, value: GameValues[Field]) => { setValues((current) => ({ ...current, [field]: value })); if (field === "title") setTitleError(""); };
  const toggleCategory = (categoryId: number) => setValues((current) => ({ ...current, categoryIds: current.categoryIds.includes(categoryId) ? current.categoryIds.filter((item) => item !== categoryId) : [...current.categoryIds, categoryId] }));
  const addGalleryUrl = () => { const value = galleryUrl.trim(); if (!value) return; setGallery((current) => [...current, createUrlGalleryItem(value)]); setGalleryUrl(""); };
  const addGalleryFile = (file: UploadFile) => setGallery((current) => [...current, createUploadGalleryItem(file)]);
  const submit = async () => { if (!values.title.trim()) { setTitleError("Digite o título do jogo antes de salvar."); return; } if (!values.description.trim() || !values.longDescription.trim() || !values.releaseDate.trim()) { setError("Preencha descrições e data de lançamento."); return; } if (values.categoryIds.length === 0) { setError("Selecione pelo menos uma categoria."); return; } if (!coverFile && !values.coverImageUrl.trim()) { setError("Escolha uma capa ou informe uma URL de fallback."); return; } try { setSaving(true); setError(""); const data = buildGameFormData(values, coverFile, gallery); if (editing) { await api.put(`/games/${id}`, data); router.replace("/admin/games" as never); } else { const created = await api.post<GameResponse>("/games", data); setValues(emptyGame); setGallery([]); setCoverFile(null); setSuccess(`Jogo criado: ${created.title}`); } } catch (requestError) { setError(getApiErrorMessage(requestError, "Não foi possível salvar o jogo.")); } finally { setSaving(false); } };
  const preview = coverFile?.uri || resolveAssetUrl(values.coverImageUrl);
  return <AdminLayout title={editing ? "Editar jogo" : "Novo jogo"} description="Edite os dados, a capa, a galeria e as categorias do jogo." backTo="/admin/games"><AdminPageState loading={loading} error={error} loadingText="Carregando formulário..." emptyText=""><View style={adminStyles.card}><AdminTextField label="Título" value={values.title} onChangeText={(value) => setField("title", value)} placeholder="Ex.: Hollow Knight" />{titleError ? <AdminNotice>{titleError}</AdminNotice> : null}<View style={styles.twoColumns}><AdminTextField label="Data de lançamento" value={values.releaseDate} onChangeText={(value) => setField("releaseDate", value)} placeholder="AAAA-MM-DD" keyboardType="numeric" /><AdminToggleField label="Jogo ativo" checked={values.isActive} onChange={(value) => setField("isActive", value)} /></View><AdminTextareaField label="Descrição curta" value={values.description} onChangeText={(value) => setField("description", value)} placeholder="Resumo exibido na loja" /><AdminTextareaField label="Descrição longa" value={values.longDescription} onChangeText={(value) => setField("longDescription", value)} placeholder="Detalhes completos do jogo" /></View><View style={adminStyles.card}><Text style={adminStyles.sectionTitle}>Categorias</Text><Text style={[adminStyles.muted, { marginTop: 5 }]}>{selectedCategories.length ? `${selectedCategories.length} categoria(s) selecionada(s).` : "Selecione pelo menos uma categoria."}</Text><View style={[adminStyles.wrap, { marginTop: 12 }]}>{categories.map((category) => { const selected = values.categoryIds.includes(category.id); return <AdminButton key={category.id} tone={selected ? "primary" : "secondary"} onPress={() => toggleCategory(category.id)}>{category.name}</AdminButton>; })}</View></View><AdminGameFormMedia values={values} coverFile={coverFile} coverPreviewUrl={preview} galleryItems={gallery} galleryUrlInput={galleryUrl} onCoverFile={setCoverFile} onClearCover={() => setCoverFile(null)} onSetCoverUrl={(value) => setField("coverImageUrl", value)} onGalleryUrlChange={setGalleryUrl} onAddGalleryUrl={addGalleryUrl} onAddGalleryFile={addGalleryFile} onMoveGallery={(key, direction) => setGallery((current) => { const index = current.findIndex((item) => item.key === key); const nextIndex = index + direction; return index < 0 || nextIndex < 0 || nextIndex >= current.length ? current : moveItem(current, index, nextIndex); })} onRemoveGallery={(key) => setGallery((current) => current.filter((item) => item.key !== key))} />{error ? <AdminNotice>{error}</AdminNotice> : null}{success ? <AdminNotice tone="success">{success}</AdminNotice> : null}<AdminFormActions onSubmit={() => void submit()} onCancel={() => router.replace("/admin/games" as never)} submitLabel="Salvar jogo" saving={saving} /></AdminPageState></AdminLayout>;
}
const styles = { twoColumns: { flexDirection: "row" as const, alignItems: "flex-end" as const, gap: 12 } };
