import { resolveAssetUrl } from "../../../services/assets";
import type { GalleryItem, GameImage, GameResponse, GameValues, UploadFile } from "../shared/admin.types";

export const emptyGame: GameValues = { title: "", description: "", longDescription: "", releaseDate: "", coverImageUrl: "", isActive: true, categoryIds: [] };
const key = () => `${Date.now()}-${Math.random().toString(16).slice(2)}`;
export function createExistingGalleryItem(image: GameImage): GalleryItem { const imageUrl = String(image.imageUrl ?? "").trim(); return { key: `existing-${image.id}`, kind: "existing", id: image.id, imageUrl, previewUrl: resolveAssetUrl(imageUrl) }; }
export function createUploadGalleryItem(file: UploadFile): GalleryItem { return { key: `file-${key()}`, kind: "file", imageUrl: "", previewUrl: file.uri, file }; }
export function createUrlGalleryItem(imageUrl: string): GalleryItem { return { key: `url-${key()}`, kind: "url", imageUrl, previewUrl: resolveAssetUrl(imageUrl) }; }
export function moveItem<T>(items: T[], from: number, to: number) { const next = [...items]; const [item] = next.splice(from, 1); next.splice(to, 0, item); return next; }
export function mapGameToValues(game: GameResponse): GameValues { return { title: game.title ?? "", description: game.description ?? "", longDescription: game.longDescription ?? "", releaseDate: game.releaseDate ?? "", coverImageUrl: game.coverImageUrl ?? "", isActive: game.isActive !== false, categoryIds: (game.categories ?? []).map((category) => category.id) }; }
export function buildGameFormData(values: GameValues, coverFile: UploadFile | null, galleryItems: GalleryItem[]) { const payload = new FormData(); const galleryFiles: UploadFile[] = []; payload.append("title", values.title.trim()); payload.append("description", values.description.trim()); payload.append("longDescription", values.longDescription.trim()); payload.append("releaseDate", values.releaseDate.trim()); payload.append("isActive", String(values.isActive)); payload.append("categoryIds", JSON.stringify(values.categoryIds)); if (values.coverImageUrl.trim()) payload.append("coverImageUrl", values.coverImageUrl.trim()); if (coverFile) payload.append("coverFile", coverFile.file ?? ({ uri: coverFile.uri, type: coverFile.type, name: coverFile.name } as unknown as Blob)); payload.append("galleryItems", JSON.stringify(galleryItems.map((item) => { if (item.kind === "existing") return { kind: "existing", id: item.id }; if (item.kind === "url") return { kind: "url", url: item.imageUrl }; const fileIndex = galleryFiles.push(item.file as UploadFile) - 1; return { kind: "file", fileIndex }; }))); galleryFiles.forEach((file) => payload.append("galleryFiles", file.file ?? ({ uri: file.uri, type: file.type, name: file.name } as unknown as Blob))); return payload; }
