import * as ImagePicker from "expo-image-picker";
import Ionicons from "@expo/vector-icons/Ionicons";
import { useEffect, useState } from "react";
import { Image, Pressable, Text, View } from "react-native";
import { router } from "expo-router";
import AdminLayout, { AdminFormActions, AdminNotice, AdminSideCard, AdminTextField, AdminToggleField, adminColors, adminStyles } from "../shared/adminShared";
import api from "../../../services/api";
import { resolvePreviewUrl } from "../../../services/assets";
import { getApiErrorMessage } from "../../../services/http";
import type { AdminPlatform, UploadFile } from "../shared/admin.types";

function createSlug(value: string) { return value.normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, ""); }
function uploadFromPicker(asset: ImagePicker.ImagePickerAsset): UploadFile { return { uri: asset.uri, name: asset.fileName ?? `plataforma-${Date.now()}.jpg`, type: asset.mimeType ?? "image/jpeg", file: asset.file }; }
function buildPayload(name: string, slug: string, iconUrl: string, isActive: boolean, iconFile: UploadFile | null) { const payload = new FormData(); payload.append("name", name); payload.append("slug", slug); payload.append("iconUrl", iconUrl.trim()); payload.append("isActive", String(isActive)); if (iconFile) payload.append("iconFile", iconFile.file ?? ({ uri: iconFile.uri, type: iconFile.type, name: iconFile.name } as unknown as Blob)); return payload; }

export default function AdminPlatformForm({ id }: { id?: string }) {
  const editing = Boolean(id); const [name, setName] = useState(""); const [slug, setSlug] = useState(""); const [iconUrl, setIconUrl] = useState(""); const [iconFile, setIconFile] = useState<UploadFile | null>(null); const [active, setActive] = useState(true); const [slugEdited, setSlugEdited] = useState(false); const [loading, setLoading] = useState(editing); const [saving, setSaving] = useState(false); const [picking, setPicking] = useState(false); const [error, setError] = useState("");
  useEffect(() => { if (!id) return; void api.get<AdminPlatform>(`/platforms/${id}`).then((data) => { setName(data.name ?? ""); setSlug(data.slug ?? ""); setIconUrl(data.iconUrl ?? ""); setActive(data.isActive !== false); setSlugEdited(true); }).catch((requestError) => setError(getApiErrorMessage(requestError, "Não foi possível carregar a plataforma."))).finally(() => setLoading(false)); }, [id]);
  const chooseImage = async () => { try { setPicking(true); const permission = await ImagePicker.requestMediaLibraryPermissionsAsync(); if (!permission.granted) { setError("Permita o acesso às suas fotos para escolher uma imagem."); return; } const result = await ImagePicker.launchImageLibraryAsync({ mediaTypes: ["images"], allowsEditing: true, quality: 0.85 }); if (!result.canceled) { setIconFile(uploadFromPicker(result.assets[0])); setError(""); } } catch { setError("Não foi possível abrir suas fotos agora."); } finally { setPicking(false); } };
  const submit = async () => { const nextName = name.trim(); const nextSlug = slug.trim(); if (!nextName) { setError("Informe o nome da plataforma."); return; } if (!nextSlug) { setError("Informe o slug da plataforma."); return; } try { setSaving(true); setError(""); const payload = buildPayload(nextName, nextSlug, iconUrl, active, iconFile); if (editing) await api.put(`/platforms/${id}`, payload); else await api.post("/platforms", payload); router.replace("/admin/platforms" as never); } catch (requestError) { setError(getApiErrorMessage(requestError, "Não foi possível salvar a plataforma.")); } finally { setSaving(false); } };
  const preview = iconFile?.uri || resolvePreviewUrl(iconUrl);
  return <AdminLayout title={editing ? "Editar plataforma" : "Nova plataforma"} description="Cadastre a plataforma com identificador único e imagem por arquivo ou URL." backTo="/admin/platforms">{loading ? <Text style={adminStyles.muted}>Carregando formulário...</Text> : <View style={adminStyles.card}><AdminTextField label="Nome" value={name} onChangeText={(value) => { setName(value); if (!slugEdited) setSlug(createSlug(value)); }} placeholder="Ex.: PlayStation 5" /><AdminTextField label="Slug" value={slug} onChangeText={(value) => { setSlugEdited(true); setSlug(createSlug(value)); }} placeholder="Ex.: playstation-5" note="Use letras, números e hífen." /><View style={styles.mediaRow}><View style={styles.preview}>{preview ? <Image source={{ uri: preview }} style={styles.previewImage} resizeMode="contain" /> : <Ionicons name="image-outline" size={30} color={adminColors.cyan} />}</View><View style={{ flex: 1, gap: 9 }}><Text style={adminStyles.label}>Imagem da plataforma</Text><Text style={adminStyles.muted}>O arquivo enviado tem prioridade sobre a URL.</Text><Pressable disabled={picking} onPress={() => void chooseImage()} style={styles.uploadButton}><Text style={{ color: adminColors.secondary, fontWeight: "700" }}>{picking ? "Abrindo fotos..." : "Escolher imagem"}</Text></Pressable>{iconFile ? <Pressable onPress={() => setIconFile(null)}><Text style={{ color: "#fecdd3", fontSize: 13 }}>Remover arquivo</Text></Pressable> : null}<AdminTextField label="URL da imagem" value={iconUrl} onChangeText={setIconUrl} placeholder="https://..." autoCapitalize="none" /></View></View><AdminToggleField label="Plataforma ativa" checked={active} onChange={setActive} />{error ? <AdminNotice>{error}</AdminNotice> : null}<AdminSideCard eyebrow="Catálogo"><Text style={adminStyles.description}>A plataforma será exibida no monitor de jogos e poderá receber preços, estoque e keys.</Text></AdminSideCard><AdminFormActions onSubmit={() => void submit()} onCancel={() => router.replace("/admin/platforms" as never)} submitLabel="Salvar" saving={saving} /></View>}</AdminLayout>;
}
const styles = { mediaRow: { flexDirection: "row" as const, alignItems: "flex-start" as const, gap: 14, borderWidth: 1, borderColor: "#1e293b", borderRadius: 18, backgroundColor: "#0f172a", padding: 14 }, preview: { width: 112, height: 112, alignItems: "center" as const, justifyContent: "center" as const, borderRadius: 16, borderWidth: 1, borderColor: "#1e293b", backgroundColor: "#020617", padding: 10 }, previewImage: { width: "100%" as const, height: "100%" as const }, uploadButton: { alignSelf: "flex-start" as const, borderWidth: 1, borderColor: "#334155", borderRadius: 999, paddingHorizontal: 14, paddingVertical: 10 } };
