import { useCallback, useEffect, useMemo, useState } from "react";
import { router } from "expo-router";
import { View } from "react-native";
import AdminLayout, { AdminButton, AdminConfirmModal, AdminPageState, adminStyles, createEmptyMeta } from "../shared/adminShared";
import api from "../../../services/api";
import { getApiErrorMessage } from "../../../services/http";
import type { AdminOfferFormState, AdminOfferItem, AdminOfferListingOption, PaginatedResponse, UploadFile } from "../shared/admin.types";
import AdminOffersForm from "./AdminOffersForm";
import AdminOffersList from "./AdminOffersList";
import AdminOffersListingPicker from "./AdminOffersListingPicker";
import { buildPlatformOptions, createEmptyOfferFormState, matchesListingSearch, mergeListingIds, normalizeDateInput } from "./adminOffers.helpers";

const PROMOTIONS_PAGE_SIZE = 12;
export default function AdminOffers() {
  const [items, setItems] = useState<AdminOfferItem[]>([]); const [meta, setMeta] = useState(createEmptyMeta(PROMOTIONS_PAGE_SIZE)); const [page, setPage] = useState(1); const [listings, setListings] = useState<AdminOfferListingOption[]>([]); const [state, setState] = useState<AdminOfferFormState>(createEmptyOfferFormState()); const [selectedIds, setSelectedIds] = useState<number[]>([]); const [initialIds, setInitialIds] = useState<number[]>([]); const [editingId, setEditingId] = useState<number | null>(null); const [coverFile, setCoverFile] = useState<UploadFile | null>(null); const [bannerFile, setBannerFile] = useState<UploadFile | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [submitError, setSubmitError] = useState(""); const [message, setMessage] = useState(""); const [saving, setSaving] = useState(false); const [deletingId, setDeletingId] = useState<number | null>(null); const [pickerOpen, setPickerOpen] = useState(false); const [pickerSearch, setPickerSearch] = useState(""); const [pendingDelete, setPendingDelete] = useState<number | null>(null);
  const platformOptions = useMemo(() => buildPlatformOptions(listings), [listings]); const filteredListings = useMemo(() => listings.filter((item) => matchesListingSearch(item, pickerSearch)), [listings, pickerSearch]); const selectedListings = useMemo(() => listings.filter((item) => selectedIds.includes(item.id)), [listings, selectedIds]);
  const load = useCallback(async (targetPage = page) => { try { setLoading(true); setError(""); const [promotionData, listingData] = await Promise.all([api.get<PaginatedResponse<AdminOfferItem>>(`/promotions?page=${targetPage}&limit=${PROMOTIONS_PAGE_SIZE}`), api.get<PaginatedResponse<AdminOfferListingOption>>("/listings?page=1&limit=100")]); setItems(promotionData.items ?? []); setMeta(promotionData.meta ?? createEmptyMeta(PROMOTIONS_PAGE_SIZE)); setListings(listingData.items ?? []); } catch (requestError) { setItems([]); setListings([]); setError(getApiErrorMessage(requestError, "Não foi possível carregar as ofertas.")); } finally { setLoading(false); } }, [page]);
  useEffect(() => { void load(page); }, [load, page]);
  const setField = (field: keyof AdminOfferFormState, value: string | boolean) => setState((current) => ({ ...current, [field]: value }));
  const reset = (clearFeedback = true) => { setState(createEmptyOfferFormState()); setSelectedIds([]); setInitialIds([]); setEditingId(null); setCoverFile(null); setBannerFile(null); setSubmitError(""); if (clearFeedback) setMessage(""); };
  const edit = (item: AdminOfferItem) => { setEditingId(item.id); setInitialIds(item.listingIds); setSelectedIds(item.listingIds); setState({ name: item.name ?? "", description: item.description ?? "", coverImageUrl: item.coverImageUrl ?? "", bannerImageUrl: item.bannerImageUrl ?? "", discountPercentage: String(item.discountPercentage ?? ""), startDate: normalizeDateInput(item.startDate), endDate: normalizeDateInput(item.endDate), isActive: Boolean(item.isActive), platformId: "" }); setSubmitError(""); setMessage(""); };
  const addPlatform = () => { const platformId = Number(state.platformId); if (!platformId) return; setSelectedIds((current) => mergeListingIds(current, listings.filter((item) => Number(item.platform?.id ?? 0) === platformId).map((item) => item.id))); setField("platformId", ""); };
  const submit = async () => { if (!state.name.trim() || !state.discountPercentage || !state.startDate || !state.endDate) { setSubmitError("Preencha nome, desconto e período da oferta."); return; } if (selectedIds.length === 0) { setSubmitError("Selecione pelo menos uma oferta para a promoção."); return; } try { setSaving(true); setSubmitError(""); setMessage(""); const payload = new FormData(); payload.append("name", state.name.trim()); payload.append("description", state.description.trim()); payload.append("coverImageUrl", state.coverImageUrl.trim()); payload.append("bannerImageUrl", state.bannerImageUrl.trim()); payload.append("discountPercentage", String(Number(state.discountPercentage))); payload.append("startDate", state.startDate); payload.append("endDate", state.endDate); payload.append("isActive", String(state.isActive)); if (coverFile) payload.append("coverFile", coverFile.file ?? ({ uri: coverFile.uri, type: coverFile.type, name: coverFile.name } as unknown as Blob)); if (bannerFile) payload.append("bannerFile", bannerFile.file ?? ({ uri: bannerFile.uri, type: bannerFile.type, name: bannerFile.name } as unknown as Blob)); const nextIds = Array.from(new Set(selectedIds)); let promotionId = editingId; if (promotionId) await api.put(`/promotions/${promotionId}`, payload); else { const created = await api.post<{ id: number }>("/promotions", payload); promotionId = created.id; } if (promotionId) { const toAdd = nextIds.filter((id) => !initialIds.includes(id)); const toRemove = initialIds.filter((id) => !nextIds.includes(id)); await Promise.all([...toAdd.map((id) => api.post(`/promotions/${promotionId}/listings/${id}`)), ...toRemove.map((id) => api.delete(`/promotions/${promotionId}/listings/${id}`))]); } const feedback = editingId ? "Oferta atualizada com sucesso." : "Oferta criada com sucesso."; const wasEditing = editingId !== null; reset(false); setMessage(feedback); await load(wasEditing ? page : 1); if (!wasEditing) setPage(1); } catch (requestError) { setSubmitError(getApiErrorMessage(requestError, "Não foi possível salvar a oferta.")); } finally { setSaving(false); } };
  const remove = async () => { if (!pendingDelete) return; try { setDeletingId(pendingDelete); await api.delete(`/promotions/${pendingDelete}`); setPendingDelete(null); if (items.length === 1 && page > 1) setPage((current) => current - 1); else await load(page); } catch (requestError) { setSubmitError(getApiErrorMessage(requestError, "Não foi possível remover a oferta.")); setPendingDelete(null); } finally { setDeletingId(null); } };
  return <AdminLayout title="Ofertas" description="Cadastre promoções simples com várias ofertas e gerencie tudo em um só lugar." backTo="/admin" actions={editingId !== null ? <AdminButton tone="secondary" onPress={reset}>Nova oferta</AdminButton> : undefined}><View style={adminStyles.wrap}><View style={{ flex: 1, minWidth: 300 }}><AdminOffersForm state={state} platformOptions={platformOptions} selectedListings={selectedListings} editing={editingId !== null} error={submitError} message={message} saving={saving} onField={setField} onSubmit={() => void submit()} onReset={reset} onAddPlatform={addPlatform} onPickListings={() => setPickerOpen(true)} onRemoveListing={(id) => setSelectedIds((current) => current.filter((item) => item !== id))} coverFile={coverFile} bannerFile={bannerFile} onCover={setCoverFile} onBanner={setBannerFile} /></View><View style={[adminStyles.card, { flex: 1, minWidth: 260 }]}><AdminButton tone="secondary" onPress={() => router.push("/admin/games" as never)}>Ir para catálogo</AdminButton></View></View><AdminPageState loading={loading} error={error} isEmpty={items.length === 0} loadingText="Carregando ofertas..." emptyText="Nenhuma oferta cadastrada."><AdminOffersList items={items} meta={meta} deletingId={deletingId} onEdit={edit} onDelete={(id) => setPendingDelete(id)} onPageChange={setPage} /></AdminPageState><AdminOffersListingPicker visible={pickerOpen} search={pickerSearch} options={filteredListings} selectedIds={selectedIds} onClose={() => { setPickerOpen(false); setPickerSearch(""); }} onSearch={setPickerSearch} onToggle={(id) => setSelectedIds((current) => current.includes(id) ? current.filter((item) => item !== id) : [...current, id])} /><AdminConfirmModal visible={pendingDelete !== null} title="Remover oferta" message="Tem certeza que deseja remover esta promoção?" tone="danger" processing={deletingId !== null} onCancel={() => setPendingDelete(null)} onConfirm={() => void remove()} /></AdminLayout>;
}
